#!/usr/bin/env bash

# Start Apache and set ServerName
echo "ServerName localhost" >> /etc/apache2/apache2.conf
service apache2 start

# Check if Apache is running
if ps aux | grep "[a]pache2" > /dev/null; then
    echo "apache2 is running"
else
    echo "apache2 is not running"
fi
